#!/usr/bin/perl

use strict;
use warnings;

$| = 1;

my %screen_map;
my ($screen, $clock);

while (<>) {
	chomp;
	if (/^clock:/) {
		s/^clock://;
		$clock = "%{r}%{B-}%{Ucyan}%{+u}%{+o}$_%{-u}%{-o}%";
	} else {
		($screen) = ($_ =~ /^\%\{(\S\d+)\}/);
		$screen_map{$screen} = $_;
	}

	foreach my $k (keys %screen_map) {
		print "$screen_map{$k}$clock", "\n";
	}
}
