#!/bin/bash

pipe="$1"
wminfo_old=

while read -r line
do
		case "$line" in
		clock:*)
			cvalue="$(echo "$line" | sed -ne 's/^clock://p')"
			clockline="|%{r}%{B-}%{Ucyan}%{+u}%{+o}${cvalue}%{-u}%{-o}%";
			;;
		*)
			wminfo_old="$line"
			;;
		esac
		printf "%s\n" "${wminfo_old}${clockline}"
done
