#!/bin/bash

pkill -0 panel || {
	echo "panel is already running" >&2
	exit 1
}

trap 'trap - TERM; kill 0' INT TERM EXIT QUIT

pipe="/tmp/cwm.pipe"

# Ascertain the DPI value.  Anything over 100 is assumed to be on a HiDPI
# display, and as such, XFT fonts, and higher font sizes are used.
this_dpi=$(xdpyinfo | \
	perl -wane '/resolution:\s+(?:(\d+)x(?:\d+))/ and print $1;')

conky -d -c ${PWD}/.conkyrc > "$pipe"

font_opts=""
geom_opts="x16"
[ $this_dpi -gt 100 ] && {
	font_opts="-f 'Book:pixelsize=25'"
	geom_opts="x25"
}

./read_status.pl | lemonbar -g $geom_opts $font_opts -p -d -B'#0000FF' -u2
