#!/bin/bash

pkill -0 panel || {
	echo "panel is already running" >&2
	exit 1
}

trap 'trap - TERM; kill 0' INT TERM EXIT QUIT

for pipe in /tmp/cwm-[0-9]*.fifo
do
	conky > "$pipe" &
done

./read_status.pl | ./barpanel | lemonbar -g x16 -p -d -B'#0000FF' -u2
